Add Dynamic Prop Categories
borisnliscool/bnl-housing pull request #17
Opened 2024-01-06 04:59 UTC by avery1227

**Description:**
This pull request adds dynamic prop categories to the project. It includes updates to localization files, code changes in the NUI Lua script, and modifications to the PropPicker component in the web application.

**Changes Made:**
- Updated the `locales/en.json` and `locales/nl.json` files to include new categories in multiple languages.
- Modified the `src/client/nui.lua` script to fetch and handle prop categories from the server.
- Enhanced the `src/web/src/components/decoration/PropPicker.svelte` component to display and select props based on prop categories.

**Testing Done:**
- Tested the changes locally to ensure that prop categories are displayed and props can be selected based on the selected category.

2024-01-06 06:57 UTC, avery1227 commented
Breaks spawning in some cases.

2024-01-06 22:21 UTC, avery1227 commented
Fixed selecting the props from the category. Should be good to go now.

2024-01-07 10:31 UTC, borisnliscool requested changes
Hey, thanks for your PR! The code looks good, there are some changes that I'd like though as specified in comments.

In one of my recent commits ([99c05c](https://github.com/borisnliscool/bnl-housing/commit/99c05c8666a9ae10d6eb022cfb83ec85afdf15f5)) I added an editorconfig and prettier config, so if you could format your code based on those that would be awesome!

2024-01-07 10:31 UTC, borisnliscool commented on src/web/src/components/decoration/PropPicker.svelte
> +            categories = JSON.parse(cats);
I don't think json encoding is required here, I think NUI requests does support sending json like objects

2024-01-07 10:31 UTC, borisnliscool commented on src/web/src/components/decoration/PropPicker.svelte
> +	$: cols = categories.length > 0 ? Math.ceil(categories.length / 2) : 1;
I had 5 rows originally, it would be nice if we could keep that

2024-01-07 10:31 UTC, borisnliscool commented on src/web/src/components/decoration/PropPicker.svelte
> +    let selectedProp = null;
I'd like some stricter typing here, previously we had:

```ts
let props: Promise<PropType[]>;
```

And something like that for categories would be nice.

2024-01-07 10:31 UTC, borisnliscool commented on src/client/nui.lua
> +	cb(json.encode(categories))
I don't think we need to json encode here

2024-01-07 10:31 UTC, borisnliscool commented on src/web/src/components/decoration/PropPicker.svelte
> +        if (!category) return []; // Return an empty array if category is not defined
What is the type of `category`? Lets force that to be a string

```ts
async function fetchProps(category: string) {
```

2024-01-07 10:31 UTC, borisnliscool commented on locales/nl.json
> +	"categories.bins": "Bakken",
Translation would be `Prullenbakken`

2024-01-07 10:31 UTC, borisnliscool commented on locales/nl.json
> +	"categories.potted": "Ingemaakt",
Translation would be `Potplanten`

2024-01-09 22:49 UTC, avery1227 commented
I'll work on the pull request updates later this week to get those all finished up.

2024-01-18 08:18 UTC, borisnliscool commented
> I'll work on the pull request updates later this week to get those all finished up.

Any progress so far? Would like to see this implemented, but if you don't have time I could finish it myself. Thanks!

2024-01-20 11:24 UTC, borisnliscool commented
Closed due to [8f5d49](https://github.com/borisnliscool/bnl-housing/commit/8f5d498ccef10dcbe83e19cc3aba27fd2582ceca).

2024-01-20 11:24 UTC, closed without merging